[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "zig"
auto-format = true

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }
[[language]]
name = "typst"
auto-format = true
formatter = { command = "typstyle" }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

[[language]]
name = "ecsl"
scope = "source.ecsl"
file-types = [ "ecsl" ]
auto-format = false
comment-token = "//"
block-comment-tokens = [
  { start = "/*", end = "*/" },
]
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "yacc"
scope = "source.yacc"
file-types = [ "y" ]
auto-format = false
comment-token = "//"
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "sublime"
scope = "source.sublime"
file-types = [ "sublime-syntax" ]
auto-format = false
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
